- hosts: all
  tasks: 
   - name: Docker
     copy: 
       src: "/etc/yum.repos.d/docker.repo"
       dest: "/etc/yum.repos.d/"

   - name: Installing Docker
     package:
         name: "docker-ce-18.06.3.ce-3.el7.x86_64"
         state: present

   - name: Starting Docker Service
     service:
          name: docker
          state: started
          enabled: yes

   - name: Install Docker SDK for python
     command: "pip3 install docker"

   - name: Download docker image
     docker_image: 
         name: httpd
         tag: latest
         source: pull

   - copy:
         src: "web.html"
         dest: "/var/www/html/index.html"

   - name: Launching HTTPD container
     docker_container:
             name: httpd
             image: httpd
             state: started
             exposed_ports:
             - "80"
             ports: 
             - "8080:80"

